version: "3.3"

services:
  cleanfolio:
    image: martinklapacz/cleanfolio
    container_name: cleanfolio
    ports:
        - ${CLEANFOLIO_PORT}:3000
    volumes:
      - cleanfolio:/cleanfolio/node_modules
    stdin_open: true
    tty: true
    networks:
     - websites

volumes:
  cleanfolio:
    driver: local

networks:
  websites:
    driver: bridge
