version: "3.3"

services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "${KANBOARD_PORT}:80"
    volumes:
      - kanboard:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins

volumes:
  kanboard:
    driver: local
  kanboard_plugins:
    driver: local

networks:
  kanboard:
    driver: bridge
