version: "3.3"

services:
  kanboard:
    image: kanboard/kanboard:latest
    ports:
      - "${KANBOARD_PORT}:80"
    volumes:
      - kanboard_data:/var/www/app/data
      - kanboard_plugins:/var/www/app/plugins
volumes:
  kanboard_data:
  kanboard_plugins:
