version: '3.3'

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling_pdf_server
    ports:
      - '${STIRLING_PDF_PORT}:8080'
    volumes:
      - stirling-pdf-tessdata:/usr/share/tesseract-ocr/5/tessdata
      - stirling-pdf-configs:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false


volumes:
  stirling-pdf-tessdata:
    driver: local
  stirling-pdf-configs:
    driver: local

networks:
  portainer:
    driver: bridge
